// Code generated by ogen, DO NOT EDIT.

package announcementsapi

import (
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

// Ref: #/components/schemas/Announcement
type Announcement struct {
	ID        uuid.UUID          `json:"id"`
	Title     string             `json:"title"`
	Content   string             `json:"content"`
	Status    AnnouncementStatus `json:"status"`
	CreatedAt time.Time          `json:"createdAt"`
	UpdatedAt time.Time          `json:"updatedAt"`
}

// GetID returns the value of ID.
func (s *Announcement) GetID() uuid.UUID {
	return s.ID
}

// GetTitle returns the value of Title.
func (s *Announcement) GetTitle() string {
	return s.Title
}

// GetContent returns the value of Content.
func (s *Announcement) GetContent() string {
	return s.Content
}

// GetStatus returns the value of Status.
func (s *Announcement) GetStatus() AnnouncementStatus {
	return s.Status
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Announcement) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Announcement) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *Announcement) SetID(val uuid.UUID) {
	s.ID = val
}

// SetTitle sets the value of Title.
func (s *Announcement) SetTitle(val string) {
	s.Title = val
}

// SetContent sets the value of Content.
func (s *Announcement) SetContent(val string) {
	s.Content = val
}

// SetStatus sets the value of Status.
func (s *Announcement) SetStatus(val AnnouncementStatus) {
	s.Status = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Announcement) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Announcement) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

func (*Announcement) createAnnouncementRes() {}
func (*Announcement) getAnnouncementRes()    {}
func (*Announcement) updateAnnouncementRes() {}

// Ref: #/components/schemas/AnnouncementInput
type AnnouncementInput struct {
	Title   string             `json:"title"`
	Content string             `json:"content"`
	Status  AnnouncementStatus `json:"status"`
}

// GetTitle returns the value of Title.
func (s *AnnouncementInput) GetTitle() string {
	return s.Title
}

// GetContent returns the value of Content.
func (s *AnnouncementInput) GetContent() string {
	return s.Content
}

// GetStatus returns the value of Status.
func (s *AnnouncementInput) GetStatus() AnnouncementStatus {
	return s.Status
}

// SetTitle sets the value of Title.
func (s *AnnouncementInput) SetTitle(val string) {
	s.Title = val
}

// SetContent sets the value of Content.
func (s *AnnouncementInput) SetContent(val string) {
	s.Content = val
}

// SetStatus sets the value of Status.
func (s *AnnouncementInput) SetStatus(val AnnouncementStatus) {
	s.Status = val
}

// Ref: #/components/schemas/AnnouncementStatus
type AnnouncementStatus string

const (
	AnnouncementStatusDraft     AnnouncementStatus = "draft"
	AnnouncementStatusPublished AnnouncementStatus = "published"
)

// AllValues returns all AnnouncementStatus values.
func (AnnouncementStatus) AllValues() []AnnouncementStatus {
	return []AnnouncementStatus{
		AnnouncementStatusDraft,
		AnnouncementStatusPublished,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AnnouncementStatus) MarshalText() ([]byte, error) {
	switch s {
	case AnnouncementStatusDraft:
		return []byte(s), nil
	case AnnouncementStatusPublished:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AnnouncementStatus) UnmarshalText(data []byte) error {
	switch AnnouncementStatus(data) {
	case AnnouncementStatusDraft:
		*s = AnnouncementStatusDraft
		return nil
	case AnnouncementStatusPublished:
		*s = AnnouncementStatusPublished
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ApiError
type ApiError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ApiError) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ApiError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ApiError) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ApiError) SetMessage(val string) {
	s.Message = val
}

func (*ApiError) createAnnouncementRes() {}
func (*ApiError) listAnnouncementsRes()  {}

type DeleteAnnouncementBadRequest ApiError

func (*DeleteAnnouncementBadRequest) deleteAnnouncementRes() {}

// DeleteAnnouncementNoContent is response for DeleteAnnouncement operation.
type DeleteAnnouncementNoContent struct{}

func (*DeleteAnnouncementNoContent) deleteAnnouncementRes() {}

type DeleteAnnouncementNotFound ApiError

func (*DeleteAnnouncementNotFound) deleteAnnouncementRes() {}

type GetAnnouncementBadRequest ApiError

func (*GetAnnouncementBadRequest) getAnnouncementRes() {}

type GetAnnouncementNotFound ApiError

func (*GetAnnouncementNotFound) getAnnouncementRes() {}

// NewOptAnnouncementStatus returns new OptAnnouncementStatus with value set to v.
func NewOptAnnouncementStatus(v AnnouncementStatus) OptAnnouncementStatus {
	return OptAnnouncementStatus{
		Value: v,
		Set:   true,
	}
}

// OptAnnouncementStatus is optional AnnouncementStatus.
type OptAnnouncementStatus struct {
	Value AnnouncementStatus
	Set   bool
}

// IsSet returns true if OptAnnouncementStatus was set.
func (o OptAnnouncementStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAnnouncementStatus) Reset() {
	var v AnnouncementStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAnnouncementStatus) SetTo(v AnnouncementStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAnnouncementStatus) Get() (v AnnouncementStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAnnouncementStatus) Or(d AnnouncementStatus) AnnouncementStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt32 returns new OptInt32 with value set to v.
func NewOptInt32(v int32) OptInt32 {
	return OptInt32{
		Value: v,
		Set:   true,
	}
}

// OptInt32 is optional int32.
type OptInt32 struct {
	Value int32
	Set   bool
}

// IsSet returns true if OptInt32 was set.
func (o OptInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt32) SetTo(v int32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt32) Get() (v int32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Page_Announcement
type PageAnnouncement struct {
	// 当前分页的项目列表.
	Items []Announcement `json:"items"`
	// 符合过滤条件的总记录数.
	Total int64 `json:"total"`
	// 分页大小限制.
	Limit int32 `json:"limit"`
	// 分页偏移量.
	Offset int32 `json:"offset"`
}

// GetItems returns the value of Items.
func (s *PageAnnouncement) GetItems() []Announcement {
	return s.Items
}

// GetTotal returns the value of Total.
func (s *PageAnnouncement) GetTotal() int64 {
	return s.Total
}

// GetLimit returns the value of Limit.
func (s *PageAnnouncement) GetLimit() int32 {
	return s.Limit
}

// GetOffset returns the value of Offset.
func (s *PageAnnouncement) GetOffset() int32 {
	return s.Offset
}

// SetItems sets the value of Items.
func (s *PageAnnouncement) SetItems(val []Announcement) {
	s.Items = val
}

// SetTotal sets the value of Total.
func (s *PageAnnouncement) SetTotal(val int64) {
	s.Total = val
}

// SetLimit sets the value of Limit.
func (s *PageAnnouncement) SetLimit(val int32) {
	s.Limit = val
}

// SetOffset sets the value of Offset.
func (s *PageAnnouncement) SetOffset(val int32) {
	s.Offset = val
}

func (*PageAnnouncement) listAnnouncementsRes() {}

type UpdateAnnouncementBadRequest ApiError

func (*UpdateAnnouncementBadRequest) updateAnnouncementRes() {}

type UpdateAnnouncementNotFound ApiError

func (*UpdateAnnouncementNotFound) updateAnnouncementRes() {}
