// Code generated by ogen, DO NOT EDIT.

package authapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// BeginOAuthLink implements beginOAuthLink operation.
	//
	// Begin linking an OAuth provider to the current, recently-authenticated account.
	//
	// POST /api/auth/oauth/{provider}/link/begin
	BeginOAuthLink(ctx context.Context, params BeginOAuthLinkParams) (BeginOAuthLinkRes, error)
	// BeginOAuthSignIn implements beginOAuthSignIn operation.
	//
	// Begin an OAuth sign-in with Google or GitHub.
	//
	// POST /api/auth/oauth/{provider}/begin
	BeginOAuthSignIn(ctx context.Context, params BeginOAuthSignInParams) (BeginOAuthSignInRes, error)
	// BeginTOTPEnrollment implements beginTOTPEnrollment operation.
	//
	// Begin enrolling a TOTP authenticator app.
	//
	// POST /api/auth/mfa/totp/enroll/begin
	BeginTOTPEnrollment(ctx context.Context) (BeginTOTPEnrollmentRes, error)
	// BeginWebAuthnAuthentication implements beginWebAuthnAuthentication operation.
	//
	// Begin a discoverable (usernameless) passkey sign-in.
	//
	// POST /api/auth/webauthn/authentication/begin
	BeginWebAuthnAuthentication(ctx context.Context) (*WebAuthnAuthenticationBeginResponse, error)
	// BeginWebAuthnRegistration implements beginWebAuthnRegistration operation.
	//
	// Begin registering a passkey for the current account.
	//
	// POST /api/auth/webauthn/registration/begin
	BeginWebAuthnRegistration(ctx context.Context) (BeginWebAuthnRegistrationRes, error)
	// CompleteOAuthLink implements completeOAuthLink operation.
	//
	// Complete linking an OAuth provider callback.
	//
	// POST /api/auth/oauth/{provider}/link/callback
	CompleteOAuthLink(ctx context.Context, req *OAuthCallbackInput, params CompleteOAuthLinkParams) (CompleteOAuthLinkRes, error)
	// CompleteOAuthSignIn implements completeOAuthSignIn operation.
	//
	// Complete an OAuth sign-in callback.
	//
	// POST /api/auth/oauth/{provider}/callback
	CompleteOAuthSignIn(ctx context.Context, req *OAuthCallbackInput, params CompleteOAuthSignInParams) (CompleteOAuthSignInRes, error)
	// ConfirmEmailVerification implements confirmEmailVerification operation.
	//
	// Confirm an email verification token.
	//
	// POST /api/auth/verification/confirm
	ConfirmEmailVerification(ctx context.Context, req *VerificationConfirmInput) (ConfirmEmailVerificationRes, error)
	// ConfirmPasswordReset implements confirmPasswordReset operation.
	//
	// Confirm a password reset token.
	//
	// POST /api/auth/password-reset/confirm
	ConfirmPasswordReset(ctx context.Context, req *PasswordResetConfirmInput) (ConfirmPasswordResetRes, error)
	// ConfirmTOTPEnrollment implements confirmTOTPEnrollment operation.
	//
	// Confirm a TOTP enrollment and receive recovery codes once.
	//
	// POST /api/auth/mfa/totp/enroll/confirm
	ConfirmTOTPEnrollment(ctx context.Context, req *TOTPEnrollmentConfirmInput) (ConfirmTOTPEnrollmentRes, error)
	// CreateAPIKey implements createAPIKey operation.
	//
	// Create an API key.
	//
	// POST /api/auth/api-keys
	CreateAPIKey(ctx context.Context, req *APIKeyCreateInput) (CreateAPIKeyRes, error)
	// FinishWebAuthnAuthentication implements finishWebAuthnAuthentication operation.
	//
	// Finish a passkey sign-in and complete sign-in.
	//
	// POST /api/auth/webauthn/authentication/finish
	FinishWebAuthnAuthentication(ctx context.Context, req *WebAuthnAuthenticationFinishInput) (FinishWebAuthnAuthenticationRes, error)
	// FinishWebAuthnRegistration implements finishWebAuthnRegistration operation.
	//
	// Finish registering a passkey for the current account.
	//
	// POST /api/auth/webauthn/registration/finish
	FinishWebAuthnRegistration(ctx context.Context, req *WebAuthnRegistrationFinishInput) (FinishWebAuthnRegistrationRes, error)
	// GetCurrentIdentity implements getCurrentIdentity operation.
	//
	// Get the current identity.
	//
	// GET /api/auth/me
	GetCurrentIdentity(ctx context.Context) (GetCurrentIdentityRes, error)
	// ListAPIKeys implements listAPIKeys operation.
	//
	// List API keys.
	//
	// GET /api/auth/api-keys
	ListAPIKeys(ctx context.Context) (ListAPIKeysRes, error)
	// ListOAuthAccounts implements listOAuthAccounts operation.
	//
	// List OAuth providers linked to the current account.
	//
	// GET /api/auth/oauth/accounts
	ListOAuthAccounts(ctx context.Context) (ListOAuthAccountsRes, error)
	// ListSessions implements listSessions operation.
	//
	// List active refresh sessions.
	//
	// GET /api/auth/sessions
	ListSessions(ctx context.Context) (ListSessionsRes, error)
	// PasswordSignIn implements passwordSignIn operation.
	//
	// Sign in with email and password.
	//
	// POST /api/auth/sign-in
	PasswordSignIn(ctx context.Context, req *PasswordSignInInput) (PasswordSignInRes, error)
	// RefreshAccessToken implements refreshAccessToken operation.
	//
	// Rotate the refresh session and issue an access token.
	//
	// POST /api/auth/refresh
	RefreshAccessToken(ctx context.Context) (RefreshAccessTokenRes, error)
	// RequestEmailOTP implements requestEmailOTP operation.
	//
	// Request an email one-time sign-in code.
	//
	// POST /api/auth/otp/request
	RequestEmailOTP(ctx context.Context, req *EmailOTPRequestInput) (RequestEmailOTPRes, error)
	// RequestEmailVerification implements requestEmailVerification operation.
	//
	// Request an email verification message.
	//
	// POST /api/auth/verification/request
	RequestEmailVerification(ctx context.Context, req *VerificationRequestInput) (RequestEmailVerificationRes, error)
	// RequestPasswordReset implements requestPasswordReset operation.
	//
	// Request a password reset message.
	//
	// POST /api/auth/password-reset/request
	RequestPasswordReset(ctx context.Context, req *VerificationRequestInput) (RequestPasswordResetRes, error)
	// RevokeAPIKey implements revokeAPIKey operation.
	//
	// Revoke an API key.
	//
	// DELETE /api/auth/api-keys/{id}
	RevokeAPIKey(ctx context.Context, params RevokeAPIKeyParams) (RevokeAPIKeyRes, error)
	// RevokeSession implements revokeSession operation.
	//
	// Revoke a refresh session.
	//
	// DELETE /api/auth/sessions/{id}
	RevokeSession(ctx context.Context, params RevokeSessionParams) (RevokeSessionRes, error)
	// SignOut implements signOut operation.
	//
	// Sign out the current refresh session.
	//
	// POST /api/auth/sign-out
	SignOut(ctx context.Context) (SignOutRes, error)
	// SignUp implements signUp operation.
	//
	// Create an account.
	//
	// POST /api/auth/sign-up
	SignUp(ctx context.Context, req *SignUpInput) (SignUpRes, error)
	// VerifyEmailOTP implements verifyEmailOTP operation.
	//
	// Verify an email one-time sign-in code and complete sign-in.
	//
	// POST /api/auth/otp/verify
	VerifyEmailOTP(ctx context.Context, req *EmailOTPVerifyInput) (VerifyEmailOTPRes, error)
	// VerifyMFAChallenge implements verifyMFAChallenge operation.
	//
	// Complete sign-in with a TOTP or recovery code.
	//
	// POST /api/auth/mfa/challenge/verify
	VerifyMFAChallenge(ctx context.Context, req *MFAChallengeVerifyInput) (VerifyMFAChallengeRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
