// Code generated by ogen, DO NOT EDIT.

package authapi

// OperationName is the ogen operation name
type OperationName = string

const (
	ConfirmEmailVerificationOperation OperationName = "ConfirmEmailVerification"
	ConfirmPasswordResetOperation     OperationName = "ConfirmPasswordReset"
	CreateAPIKeyOperation             OperationName = "CreateAPIKey"
	GetCurrentIdentityOperation       OperationName = "GetCurrentIdentity"
	ListAPIKeysOperation              OperationName = "ListAPIKeys"
	ListSessionsOperation             OperationName = "ListSessions"
	PasswordSignInOperation           OperationName = "PasswordSignIn"
	RefreshAccessTokenOperation       OperationName = "RefreshAccessToken"
	RequestEmailVerificationOperation OperationName = "RequestEmailVerification"
	RequestPasswordResetOperation     OperationName = "RequestPasswordReset"
	RevokeAPIKeyOperation             OperationName = "RevokeAPIKey"
	RevokeSessionOperation            OperationName = "RevokeSession"
	SignOutOperation                  OperationName = "SignOut"
	SignUpOperation                   OperationName = "SignUp"
)
