// Code generated by ogen, DO NOT EDIT.
package authapi

type BeginOAuthLinkRes interface {
	beginOAuthLinkRes()
}

type BeginOAuthSignInRes interface {
	beginOAuthSignInRes()
}

type BeginTOTPEnrollmentRes interface {
	beginTOTPEnrollmentRes()
}

type BeginWebAuthnRegistrationRes interface {
	beginWebAuthnRegistrationRes()
}

type CompleteOAuthLinkRes interface {
	completeOAuthLinkRes()
}

type CompleteOAuthSignInRes interface {
	completeOAuthSignInRes()
}

type ConfirmEmailVerificationRes interface {
	confirmEmailVerificationRes()
}

type ConfirmPasswordResetRes interface {
	confirmPasswordResetRes()
}

type ConfirmTOTPEnrollmentRes interface {
	confirmTOTPEnrollmentRes()
}

type CreateAPIKeyRes interface {
	createAPIKeyRes()
}

type FinishWebAuthnAuthenticationRes interface {
	finishWebAuthnAuthenticationRes()
}

type FinishWebAuthnRegistrationRes interface {
	finishWebAuthnRegistrationRes()
}

type GetCurrentIdentityRes interface {
	getCurrentIdentityRes()
}

type ListAPIKeysRes interface {
	listAPIKeysRes()
}

type ListOAuthAccountsRes interface {
	listOAuthAccountsRes()
}

type ListSessionsRes interface {
	listSessionsRes()
}

type PasswordSignInRes interface {
	passwordSignInRes()
}

type RefreshAccessTokenRes interface {
	refreshAccessTokenRes()
}

type RequestEmailOTPRes interface {
	requestEmailOTPRes()
}

type RequestEmailVerificationRes interface {
	requestEmailVerificationRes()
}

type RequestPasswordResetRes interface {
	requestPasswordResetRes()
}

type RevokeAPIKeyRes interface {
	revokeAPIKeyRes()
}

type RevokeSessionRes interface {
	revokeSessionRes()
}

type SignOutRes interface {
	signOutRes()
}

type SignUpRes interface {
	signUpRes()
}

type VerifyEmailOTPRes interface {
	verifyEmailOTPRes()
}

type VerifyMFAChallengeRes interface {
	verifyMFAChallengeRes()
}
