// Code generated by ogen, DO NOT EDIT.
package organizationsapi

type AcceptInvitationRes interface {
	acceptInvitationRes()
}

type CreateInvitationRes interface {
	createInvitationRes()
}

type CreateOrganizationRes interface {
	createOrganizationRes()
}

type DeleteOrganizationRes interface {
	deleteOrganizationRes()
}

type GetOrganizationRes interface {
	getOrganizationRes()
}

type ListInvitationsRes interface {
	listInvitationsRes()
}

type ListMembersRes interface {
	listMembersRes()
}

type ListUserOrganizationsRes interface {
	listUserOrganizationsRes()
}

type RemoveMemberRes interface {
	removeMemberRes()
}

type RevokeInvitationRes interface {
	revokeInvitationRes()
}

type UpdateMemberRoleRes interface {
	updateMemberRoleRes()
}

type UpdateOrganizationRes interface {
	updateOrganizationRes()
}
