// Code generated by ogen, DO NOT EDIT.

package organizationsapi

import (
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

type AcceptInvitationBadRequest ApiError

func (*AcceptInvitationBadRequest) acceptInvitationRes() {}

// Ref: #/components/schemas/AcceptInvitationInput
type AcceptInvitationInput struct {
	Token string `json:"token"`
}

// GetToken returns the value of Token.
func (s *AcceptInvitationInput) GetToken() string {
	return s.Token
}

// SetToken sets the value of Token.
func (s *AcceptInvitationInput) SetToken(val string) {
	s.Token = val
}

type AcceptInvitationNotFound ApiError

func (*AcceptInvitationNotFound) acceptInvitationRes() {}

type AcceptInvitationUnauthorized ApiError

func (*AcceptInvitationUnauthorized) acceptInvitationRes() {}

// Ref: #/components/schemas/ApiError
type ApiError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ApiError) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ApiError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ApiError) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ApiError) SetMessage(val string) {
	s.Message = val
}

func (*ApiError) listUserOrganizationsRes() {}

type CreateInvitationBadRequest ApiError

func (*CreateInvitationBadRequest) createInvitationRes() {}

type CreateInvitationConflict ApiError

func (*CreateInvitationConflict) createInvitationRes() {}

type CreateInvitationForbidden ApiError

func (*CreateInvitationForbidden) createInvitationRes() {}

// Ref: #/components/schemas/CreateInvitationInput
type CreateInvitationInput struct {
	Email string           `json:"email"`
	Role  OrganizationRole `json:"role"`
}

// GetEmail returns the value of Email.
func (s *CreateInvitationInput) GetEmail() string {
	return s.Email
}

// GetRole returns the value of Role.
func (s *CreateInvitationInput) GetRole() OrganizationRole {
	return s.Role
}

// SetEmail sets the value of Email.
func (s *CreateInvitationInput) SetEmail(val string) {
	s.Email = val
}

// SetRole sets the value of Role.
func (s *CreateInvitationInput) SetRole(val OrganizationRole) {
	s.Role = val
}

type CreateInvitationNotFound ApiError

func (*CreateInvitationNotFound) createInvitationRes() {}

type CreateInvitationUnauthorized ApiError

func (*CreateInvitationUnauthorized) createInvitationRes() {}

type CreateOrganizationBadRequest ApiError

func (*CreateOrganizationBadRequest) createOrganizationRes() {}

type CreateOrganizationConflict ApiError

func (*CreateOrganizationConflict) createOrganizationRes() {}

// Ref: #/components/schemas/CreateOrganizationInput
type CreateOrganizationInput struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
}

// GetSlug returns the value of Slug.
func (s *CreateOrganizationInput) GetSlug() string {
	return s.Slug
}

// GetName returns the value of Name.
func (s *CreateOrganizationInput) GetName() string {
	return s.Name
}

// SetSlug sets the value of Slug.
func (s *CreateOrganizationInput) SetSlug(val string) {
	s.Slug = val
}

// SetName sets the value of Name.
func (s *CreateOrganizationInput) SetName(val string) {
	s.Name = val
}

type CreateOrganizationUnauthorized ApiError

func (*CreateOrganizationUnauthorized) createOrganizationRes() {}

// Ref: #/components/schemas/CreatedInvitationResponse
type CreatedInvitationResponse struct {
	Invitation OrganizationInvitation `json:"invitation"`
	Token      string                 `json:"token"`
}

// GetInvitation returns the value of Invitation.
func (s *CreatedInvitationResponse) GetInvitation() OrganizationInvitation {
	return s.Invitation
}

// GetToken returns the value of Token.
func (s *CreatedInvitationResponse) GetToken() string {
	return s.Token
}

// SetInvitation sets the value of Invitation.
func (s *CreatedInvitationResponse) SetInvitation(val OrganizationInvitation) {
	s.Invitation = val
}

// SetToken sets the value of Token.
func (s *CreatedInvitationResponse) SetToken(val string) {
	s.Token = val
}

func (*CreatedInvitationResponse) createInvitationRes() {}

type DeleteOrganizationForbidden ApiError

func (*DeleteOrganizationForbidden) deleteOrganizationRes() {}

// DeleteOrganizationNoContent is response for DeleteOrganization operation.
type DeleteOrganizationNoContent struct{}

func (*DeleteOrganizationNoContent) deleteOrganizationRes() {}

type DeleteOrganizationNotFound ApiError

func (*DeleteOrganizationNotFound) deleteOrganizationRes() {}

type DeleteOrganizationUnauthorized ApiError

func (*DeleteOrganizationUnauthorized) deleteOrganizationRes() {}

type GetOrganizationForbidden ApiError

func (*GetOrganizationForbidden) getOrganizationRes() {}

type GetOrganizationNotFound ApiError

func (*GetOrganizationNotFound) getOrganizationRes() {}

type GetOrganizationUnauthorized ApiError

func (*GetOrganizationUnauthorized) getOrganizationRes() {}

type ListInvitationsForbidden ApiError

func (*ListInvitationsForbidden) listInvitationsRes() {}

type ListInvitationsNotFound ApiError

func (*ListInvitationsNotFound) listInvitationsRes() {}

type ListInvitationsOKApplicationJSON []OrganizationInvitation

func (*ListInvitationsOKApplicationJSON) listInvitationsRes() {}

type ListInvitationsUnauthorized ApiError

func (*ListInvitationsUnauthorized) listInvitationsRes() {}

type ListMembersForbidden ApiError

func (*ListMembersForbidden) listMembersRes() {}

type ListMembersNotFound ApiError

func (*ListMembersNotFound) listMembersRes() {}

type ListMembersOKApplicationJSON []OrganizationMembership

func (*ListMembersOKApplicationJSON) listMembersRes() {}

type ListMembersUnauthorized ApiError

func (*ListMembersUnauthorized) listMembersRes() {}

type ListUserOrganizationsOKApplicationJSON []OrganizationWithRole

func (*ListUserOrganizationsOKApplicationJSON) listUserOrganizationsRes() {}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Organization
type Organization struct {
	ID        uuid.UUID `json:"id"`
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// GetID returns the value of ID.
func (s *Organization) GetID() uuid.UUID {
	return s.ID
}

// GetSlug returns the value of Slug.
func (s *Organization) GetSlug() string {
	return s.Slug
}

// GetName returns the value of Name.
func (s *Organization) GetName() string {
	return s.Name
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Organization) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Organization) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *Organization) SetID(val uuid.UUID) {
	s.ID = val
}

// SetSlug sets the value of Slug.
func (s *Organization) SetSlug(val string) {
	s.Slug = val
}

// SetName sets the value of Name.
func (s *Organization) SetName(val string) {
	s.Name = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Organization) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Organization) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

func (*Organization) createOrganizationRes() {}
func (*Organization) getOrganizationRes()    {}
func (*Organization) updateOrganizationRes() {}

// Ref: #/components/schemas/OrganizationInvitation
type OrganizationInvitation struct {
	ID             uuid.UUID        `json:"id"`
	OrganizationId uuid.UUID        `json:"organizationId"`
	Email          string           `json:"email"`
	Role           OrganizationRole `json:"role"`
	ExpiresAt      time.Time        `json:"expiresAt"`
	CreatedAt      time.Time        `json:"createdAt"`
}

// GetID returns the value of ID.
func (s *OrganizationInvitation) GetID() uuid.UUID {
	return s.ID
}

// GetOrganizationId returns the value of OrganizationId.
func (s *OrganizationInvitation) GetOrganizationId() uuid.UUID {
	return s.OrganizationId
}

// GetEmail returns the value of Email.
func (s *OrganizationInvitation) GetEmail() string {
	return s.Email
}

// GetRole returns the value of Role.
func (s *OrganizationInvitation) GetRole() OrganizationRole {
	return s.Role
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *OrganizationInvitation) GetExpiresAt() time.Time {
	return s.ExpiresAt
}

// GetCreatedAt returns the value of CreatedAt.
func (s *OrganizationInvitation) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *OrganizationInvitation) SetID(val uuid.UUID) {
	s.ID = val
}

// SetOrganizationId sets the value of OrganizationId.
func (s *OrganizationInvitation) SetOrganizationId(val uuid.UUID) {
	s.OrganizationId = val
}

// SetEmail sets the value of Email.
func (s *OrganizationInvitation) SetEmail(val string) {
	s.Email = val
}

// SetRole sets the value of Role.
func (s *OrganizationInvitation) SetRole(val OrganizationRole) {
	s.Role = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *OrganizationInvitation) SetExpiresAt(val time.Time) {
	s.ExpiresAt = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *OrganizationInvitation) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// Ref: #/components/schemas/OrganizationMembership
type OrganizationMembership struct {
	ID             uuid.UUID        `json:"id"`
	OrganizationId uuid.UUID        `json:"organizationId"`
	UserId         uuid.UUID        `json:"userId"`
	Email          OptString        `json:"email"`
	Role           OrganizationRole `json:"role"`
	CreatedAt      time.Time        `json:"createdAt"`
	UpdatedAt      time.Time        `json:"updatedAt"`
}

// GetID returns the value of ID.
func (s *OrganizationMembership) GetID() uuid.UUID {
	return s.ID
}

// GetOrganizationId returns the value of OrganizationId.
func (s *OrganizationMembership) GetOrganizationId() uuid.UUID {
	return s.OrganizationId
}

// GetUserId returns the value of UserId.
func (s *OrganizationMembership) GetUserId() uuid.UUID {
	return s.UserId
}

// GetEmail returns the value of Email.
func (s *OrganizationMembership) GetEmail() OptString {
	return s.Email
}

// GetRole returns the value of Role.
func (s *OrganizationMembership) GetRole() OrganizationRole {
	return s.Role
}

// GetCreatedAt returns the value of CreatedAt.
func (s *OrganizationMembership) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *OrganizationMembership) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *OrganizationMembership) SetID(val uuid.UUID) {
	s.ID = val
}

// SetOrganizationId sets the value of OrganizationId.
func (s *OrganizationMembership) SetOrganizationId(val uuid.UUID) {
	s.OrganizationId = val
}

// SetUserId sets the value of UserId.
func (s *OrganizationMembership) SetUserId(val uuid.UUID) {
	s.UserId = val
}

// SetEmail sets the value of Email.
func (s *OrganizationMembership) SetEmail(val OptString) {
	s.Email = val
}

// SetRole sets the value of Role.
func (s *OrganizationMembership) SetRole(val OrganizationRole) {
	s.Role = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *OrganizationMembership) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *OrganizationMembership) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

func (*OrganizationMembership) acceptInvitationRes() {}
func (*OrganizationMembership) updateMemberRoleRes() {}

// Ref: #/components/schemas/OrganizationRole
type OrganizationRole string

const (
	OrganizationRoleOwner  OrganizationRole = "owner"
	OrganizationRoleAdmin  OrganizationRole = "admin"
	OrganizationRoleMember OrganizationRole = "member"
	OrganizationRoleViewer OrganizationRole = "viewer"
)

// AllValues returns all OrganizationRole values.
func (OrganizationRole) AllValues() []OrganizationRole {
	return []OrganizationRole{
		OrganizationRoleOwner,
		OrganizationRoleAdmin,
		OrganizationRoleMember,
		OrganizationRoleViewer,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrganizationRole) MarshalText() ([]byte, error) {
	switch s {
	case OrganizationRoleOwner:
		return []byte(s), nil
	case OrganizationRoleAdmin:
		return []byte(s), nil
	case OrganizationRoleMember:
		return []byte(s), nil
	case OrganizationRoleViewer:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrganizationRole) UnmarshalText(data []byte) error {
	switch OrganizationRole(data) {
	case OrganizationRoleOwner:
		*s = OrganizationRoleOwner
		return nil
	case OrganizationRoleAdmin:
		*s = OrganizationRoleAdmin
		return nil
	case OrganizationRoleMember:
		*s = OrganizationRoleMember
		return nil
	case OrganizationRoleViewer:
		*s = OrganizationRoleViewer
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/OrganizationWithRole
type OrganizationWithRole struct {
	ID        uuid.UUID        `json:"id"`
	Slug      string           `json:"slug"`
	Name      string           `json:"name"`
	Role      OrganizationRole `json:"role"`
	CreatedAt time.Time        `json:"createdAt"`
	UpdatedAt time.Time        `json:"updatedAt"`
}

// GetID returns the value of ID.
func (s *OrganizationWithRole) GetID() uuid.UUID {
	return s.ID
}

// GetSlug returns the value of Slug.
func (s *OrganizationWithRole) GetSlug() string {
	return s.Slug
}

// GetName returns the value of Name.
func (s *OrganizationWithRole) GetName() string {
	return s.Name
}

// GetRole returns the value of Role.
func (s *OrganizationWithRole) GetRole() OrganizationRole {
	return s.Role
}

// GetCreatedAt returns the value of CreatedAt.
func (s *OrganizationWithRole) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *OrganizationWithRole) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *OrganizationWithRole) SetID(val uuid.UUID) {
	s.ID = val
}

// SetSlug sets the value of Slug.
func (s *OrganizationWithRole) SetSlug(val string) {
	s.Slug = val
}

// SetName sets the value of Name.
func (s *OrganizationWithRole) SetName(val string) {
	s.Name = val
}

// SetRole sets the value of Role.
func (s *OrganizationWithRole) SetRole(val OrganizationRole) {
	s.Role = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *OrganizationWithRole) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *OrganizationWithRole) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

type RemoveMemberBadRequest ApiError

func (*RemoveMemberBadRequest) removeMemberRes() {}

type RemoveMemberForbidden ApiError

func (*RemoveMemberForbidden) removeMemberRes() {}

// RemoveMemberNoContent is response for RemoveMember operation.
type RemoveMemberNoContent struct{}

func (*RemoveMemberNoContent) removeMemberRes() {}

type RemoveMemberNotFound ApiError

func (*RemoveMemberNotFound) removeMemberRes() {}

type RemoveMemberUnauthorized ApiError

func (*RemoveMemberUnauthorized) removeMemberRes() {}

type RevokeInvitationForbidden ApiError

func (*RevokeInvitationForbidden) revokeInvitationRes() {}

// RevokeInvitationNoContent is response for RevokeInvitation operation.
type RevokeInvitationNoContent struct{}

func (*RevokeInvitationNoContent) revokeInvitationRes() {}

type RevokeInvitationNotFound ApiError

func (*RevokeInvitationNotFound) revokeInvitationRes() {}

type RevokeInvitationUnauthorized ApiError

func (*RevokeInvitationUnauthorized) revokeInvitationRes() {}

type UpdateMemberRoleBadRequest ApiError

func (*UpdateMemberRoleBadRequest) updateMemberRoleRes() {}

type UpdateMemberRoleForbidden ApiError

func (*UpdateMemberRoleForbidden) updateMemberRoleRes() {}

type UpdateMemberRoleNotFound ApiError

func (*UpdateMemberRoleNotFound) updateMemberRoleRes() {}

type UpdateMemberRoleUnauthorized ApiError

func (*UpdateMemberRoleUnauthorized) updateMemberRoleRes() {}

// Ref: #/components/schemas/UpdateMembershipRoleInput
type UpdateMembershipRoleInput struct {
	Role OrganizationRole `json:"role"`
}

// GetRole returns the value of Role.
func (s *UpdateMembershipRoleInput) GetRole() OrganizationRole {
	return s.Role
}

// SetRole sets the value of Role.
func (s *UpdateMembershipRoleInput) SetRole(val OrganizationRole) {
	s.Role = val
}

type UpdateOrganizationBadRequest ApiError

func (*UpdateOrganizationBadRequest) updateOrganizationRes() {}

type UpdateOrganizationConflict ApiError

func (*UpdateOrganizationConflict) updateOrganizationRes() {}

type UpdateOrganizationForbidden ApiError

func (*UpdateOrganizationForbidden) updateOrganizationRes() {}

// Ref: #/components/schemas/UpdateOrganizationInput
type UpdateOrganizationInput struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
}

// GetSlug returns the value of Slug.
func (s *UpdateOrganizationInput) GetSlug() string {
	return s.Slug
}

// GetName returns the value of Name.
func (s *UpdateOrganizationInput) GetName() string {
	return s.Name
}

// SetSlug sets the value of Slug.
func (s *UpdateOrganizationInput) SetSlug(val string) {
	s.Slug = val
}

// SetName sets the value of Name.
func (s *UpdateOrganizationInput) SetName(val string) {
	s.Name = val
}

type UpdateOrganizationNotFound ApiError

func (*UpdateOrganizationNotFound) updateOrganizationRes() {}

type UpdateOrganizationUnauthorized ApiError

func (*UpdateOrganizationUnauthorized) updateOrganizationRes() {}
