// Code generated by ogen, DO NOT EDIT.

package organizationsapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AcceptInvitation implements acceptInvitation operation.
	//
	// Accept an organization invitation.
	//
	// POST /api/organizations/invitations/accept
	AcceptInvitation(ctx context.Context, req *AcceptInvitationInput) (AcceptInvitationRes, error)
	// CreateInvitation implements createInvitation operation.
	//
	// Invite a member to the organization.
	//
	// POST /api/organizations/{organizationId}/invitations
	CreateInvitation(ctx context.Context, req *CreateInvitationInput, params CreateInvitationParams) (CreateInvitationRes, error)
	// CreateOrganization implements createOrganization operation.
	//
	// Create an organization.
	//
	// POST /api/organizations
	CreateOrganization(ctx context.Context, req *CreateOrganizationInput) (CreateOrganizationRes, error)
	// DeleteOrganization implements deleteOrganization operation.
	//
	// Delete an organization.
	//
	// DELETE /api/organizations/{organizationId}
	DeleteOrganization(ctx context.Context, params DeleteOrganizationParams) (DeleteOrganizationRes, error)
	// GetOrganization implements getOrganization operation.
	//
	// Get organization details.
	//
	// GET /api/organizations/{organizationId}
	GetOrganization(ctx context.Context, params GetOrganizationParams) (GetOrganizationRes, error)
	// ListInvitations implements listInvitations operation.
	//
	// List active organization invitations.
	//
	// GET /api/organizations/{organizationId}/invitations
	ListInvitations(ctx context.Context, params ListInvitationsParams) (ListInvitationsRes, error)
	// ListMembers implements listMembers operation.
	//
	// List organization members.
	//
	// GET /api/organizations/{organizationId}/members
	ListMembers(ctx context.Context, params ListMembersParams) (ListMembersRes, error)
	// ListUserOrganizations implements listUserOrganizations operation.
	//
	// List organizations for the current user.
	//
	// GET /api/organizations
	ListUserOrganizations(ctx context.Context) (ListUserOrganizationsRes, error)
	// RemoveMember implements removeMember operation.
	//
	// Remove a member from the organization.
	//
	// DELETE /api/organizations/{organizationId}/members/{userId}
	RemoveMember(ctx context.Context, params RemoveMemberParams) (RemoveMemberRes, error)
	// RevokeInvitation implements revokeInvitation operation.
	//
	// Revoke an organization invitation.
	//
	// DELETE /api/organizations/{organizationId}/invitations/{invitationId}
	RevokeInvitation(ctx context.Context, params RevokeInvitationParams) (RevokeInvitationRes, error)
	// UpdateMemberRole implements updateMemberRole operation.
	//
	// Update a member's role.
	//
	// PUT /api/organizations/{organizationId}/members/{userId}
	UpdateMemberRole(ctx context.Context, req *UpdateMembershipRoleInput, params UpdateMemberRoleParams) (UpdateMemberRoleRes, error)
	// UpdateOrganization implements updateOrganization operation.
	//
	// Update organization details.
	//
	// PUT /api/organizations/{organizationId}
	UpdateOrganization(ctx context.Context, req *UpdateOrganizationInput, params UpdateOrganizationParams) (UpdateOrganizationRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
