// Code generated by ogen, DO NOT EDIT.

package organizationsapi

// OperationName is the ogen operation name
type OperationName = string

const (
	AcceptInvitationOperation      OperationName = "AcceptInvitation"
	CreateInvitationOperation      OperationName = "CreateInvitation"
	CreateOrganizationOperation    OperationName = "CreateOrganization"
	DeleteOrganizationOperation    OperationName = "DeleteOrganization"
	GetOrganizationOperation       OperationName = "GetOrganization"
	ListInvitationsOperation       OperationName = "ListInvitations"
	ListMembersOperation           OperationName = "ListMembers"
	ListUserOrganizationsOperation OperationName = "ListUserOrganizations"
	RemoveMemberOperation          OperationName = "RemoveMember"
	RevokeInvitationOperation      OperationName = "RevokeInvitation"
	UpdateMemberRoleOperation      OperationName = "UpdateMemberRole"
	UpdateOrganizationOperation    OperationName = "UpdateOrganization"
)
