// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBillingAccount = `-- name: CreateBillingAccount :one
INSERT INTO billing_accounts (organization_id, stripe_customer_id)
VALUES ($1, $2)
ON CONFLICT (organization_id) DO UPDATE
SET stripe_customer_id = billing_accounts.stripe_customer_id
RETURNING id, organization_id, stripe_customer_id, created_at, updated_at
`

type CreateBillingAccountParams struct {
	OrganizationID   pgtype.UUID `db:"organization_id" json:"organization_id"`
	StripeCustomerID string      `db:"stripe_customer_id" json:"stripe_customer_id"`
}

func (q *Queries) CreateBillingAccount(ctx context.Context, arg CreateBillingAccountParams) (BillingAccount, error) {
	row := q.db.QueryRow(ctx, createBillingAccount, arg.OrganizationID, arg.StripeCustomerID)
	var i BillingAccount
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StripeCustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCheckoutSession = `-- name: CreateCheckoutSession :one
INSERT INTO checkout_sessions (billing_account_id, stripe_checkout_session_id, price_key, mode, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, billing_account_id, stripe_checkout_session_id, price_key, mode, status, created_at, updated_at
`

type CreateCheckoutSessionParams struct {
	BillingAccountID        pgtype.UUID `db:"billing_account_id" json:"billing_account_id"`
	StripeCheckoutSessionID string      `db:"stripe_checkout_session_id" json:"stripe_checkout_session_id"`
	PriceKey                string      `db:"price_key" json:"price_key"`
	Mode                    string      `db:"mode" json:"mode"`
	Status                  string      `db:"status" json:"status"`
}

func (q *Queries) CreateCheckoutSession(ctx context.Context, arg CreateCheckoutSessionParams) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, createCheckoutSession,
		arg.BillingAccountID,
		arg.StripeCheckoutSessionID,
		arg.PriceKey,
		arg.Mode,
		arg.Status,
	)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.BillingAccountID,
		&i.StripeCheckoutSessionID,
		&i.PriceKey,
		&i.Mode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBillingAccountByOrganization = `-- name: GetBillingAccountByOrganization :one
SELECT id, organization_id, stripe_customer_id, created_at, updated_at
FROM billing_accounts
WHERE organization_id = $1
`

func (q *Queries) GetBillingAccountByOrganization(ctx context.Context, organizationID pgtype.UUID) (BillingAccount, error) {
	row := q.db.QueryRow(ctx, getBillingAccountByOrganization, organizationID)
	var i BillingAccount
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StripeCustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBillingAccountByStripeCustomerID = `-- name: GetBillingAccountByStripeCustomerID :one
SELECT id, organization_id, stripe_customer_id, created_at, updated_at
FROM billing_accounts
WHERE stripe_customer_id = $1
`

func (q *Queries) GetBillingAccountByStripeCustomerID(ctx context.Context, stripeCustomerID string) (BillingAccount, error) {
	row := q.db.QueryRow(ctx, getBillingAccountByStripeCustomerID, stripeCustomerID)
	var i BillingAccount
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StripeCustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCheckoutSessionByStripeID = `-- name: GetCheckoutSessionByStripeID :one
SELECT id, billing_account_id, stripe_checkout_session_id, price_key, mode, status, created_at, updated_at
FROM checkout_sessions
WHERE stripe_checkout_session_id = $1
`

func (q *Queries) GetCheckoutSessionByStripeID(ctx context.Context, stripeCheckoutSessionID string) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, getCheckoutSessionByStripeID, stripeCheckoutSessionID)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.BillingAccountID,
		&i.StripeCheckoutSessionID,
		&i.PriceKey,
		&i.Mode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByStripeID = `-- name: GetSubscriptionByStripeID :one
SELECT id, billing_account_id, stripe_subscription_id, price_key, status,
       current_period_end, cancel_at_period_end, last_event_created_at, created_at, updated_at
FROM subscriptions
WHERE stripe_subscription_id = $1
`

func (q *Queries) GetSubscriptionByStripeID(ctx context.Context, stripeSubscriptionID string) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByStripeID, stripeSubscriptionID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.BillingAccountID,
		&i.StripeSubscriptionID,
		&i.PriceKey,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.LastEventCreatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasEntitlement = `-- name: HasEntitlement :one
SELECT EXISTS (
    SELECT 1
    FROM entitlements
    WHERE organization_id = $1
      AND feature_key = $2
      AND enabled = true
      AND (expires_at IS NULL OR expires_at > now())
) AS has_entitlement
`

type HasEntitlementParams struct {
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	FeatureKey     string      `db:"feature_key" json:"feature_key"`
}

func (q *Queries) HasEntitlement(ctx context.Context, arg HasEntitlementParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasEntitlement, arg.OrganizationID, arg.FeatureKey)
	var has_entitlement bool
	err := row.Scan(&has_entitlement)
	return has_entitlement, err
}

const insertOneTimePurchase = `-- name: InsertOneTimePurchase :one
INSERT INTO one_time_purchases (billing_account_id, stripe_checkout_session_id, price_key, amount_minor_units, currency, status)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (stripe_checkout_session_id) DO NOTHING
RETURNING id, billing_account_id, stripe_checkout_session_id, price_key, amount_minor_units, currency, status, created_at
`

type InsertOneTimePurchaseParams struct {
	BillingAccountID        pgtype.UUID `db:"billing_account_id" json:"billing_account_id"`
	StripeCheckoutSessionID string      `db:"stripe_checkout_session_id" json:"stripe_checkout_session_id"`
	PriceKey                string      `db:"price_key" json:"price_key"`
	AmountMinorUnits        int64       `db:"amount_minor_units" json:"amount_minor_units"`
	Currency                string      `db:"currency" json:"currency"`
	Status                  string      `db:"status" json:"status"`
}

// ON CONFLICT DO NOTHING makes re-delivery of the same checkout session's
// completion event idempotent at the row level, independent of the
// stripe_webhook_events dedup (defense in depth).
func (q *Queries) InsertOneTimePurchase(ctx context.Context, arg InsertOneTimePurchaseParams) (OneTimePurchase, error) {
	row := q.db.QueryRow(ctx, insertOneTimePurchase,
		arg.BillingAccountID,
		arg.StripeCheckoutSessionID,
		arg.PriceKey,
		arg.AmountMinorUnits,
		arg.Currency,
		arg.Status,
	)
	var i OneTimePurchase
	err := row.Scan(
		&i.ID,
		&i.BillingAccountID,
		&i.StripeCheckoutSessionID,
		&i.PriceKey,
		&i.AmountMinorUnits,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertWebhookEvent = `-- name: InsertWebhookEvent :one
INSERT INTO stripe_webhook_events (stripe_event_id, event_type, event_created_at)
VALUES ($1, $2, $3)
ON CONFLICT (stripe_event_id) DO NOTHING
RETURNING id, stripe_event_id, event_type, event_created_at, received_at
`

type InsertWebhookEventParams struct {
	StripeEventID  string             `db:"stripe_event_id" json:"stripe_event_id"`
	EventType      string             `db:"event_type" json:"event_type"`
	EventCreatedAt pgtype.Timestamptz `db:"event_created_at" json:"event_created_at"`
}

// Single-statement, constraint-based idempotency check: ON CONFLICT DO
// NOTHING means a duplicate delivery of the same Stripe event ID returns no
// row (not an error), which the caller treats as "already processed".
func (q *Queries) InsertWebhookEvent(ctx context.Context, arg InsertWebhookEventParams) (StripeWebhookEvent, error) {
	row := q.db.QueryRow(ctx, insertWebhookEvent, arg.StripeEventID, arg.EventType, arg.EventCreatedAt)
	var i StripeWebhookEvent
	err := row.Scan(
		&i.ID,
		&i.StripeEventID,
		&i.EventType,
		&i.EventCreatedAt,
		&i.ReceivedAt,
	)
	return i, err
}

const listEntitlementsForOrganization = `-- name: ListEntitlementsForOrganization :many
SELECT id, organization_id, feature_key, source, enabled, expires_at, subscription_id, one_time_purchase_id, created_at, updated_at
FROM entitlements
WHERE organization_id = $1
ORDER BY feature_key, source
`

func (q *Queries) ListEntitlementsForOrganization(ctx context.Context, organizationID pgtype.UUID) ([]Entitlement, error) {
	rows, err := q.db.Query(ctx, listEntitlementsForOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entitlement{}
	for rows.Next() {
		var i Entitlement
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.FeatureKey,
			&i.Source,
			&i.Enabled,
			&i.ExpiresAt,
			&i.SubscriptionID,
			&i.OneTimePurchaseID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOneTimePurchasesForBillingAccount = `-- name: ListOneTimePurchasesForBillingAccount :many
SELECT id, billing_account_id, stripe_checkout_session_id, price_key, amount_minor_units, currency, status, created_at
FROM one_time_purchases
WHERE billing_account_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOneTimePurchasesForBillingAccount(ctx context.Context, billingAccountID pgtype.UUID) ([]OneTimePurchase, error) {
	rows, err := q.db.Query(ctx, listOneTimePurchasesForBillingAccount, billingAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OneTimePurchase{}
	for rows.Next() {
		var i OneTimePurchase
		if err := rows.Scan(
			&i.ID,
			&i.BillingAccountID,
			&i.StripeCheckoutSessionID,
			&i.PriceKey,
			&i.AmountMinorUnits,
			&i.Currency,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsForBillingAccount = `-- name: ListSubscriptionsForBillingAccount :many
SELECT id, billing_account_id, stripe_subscription_id, price_key, status,
       current_period_end, cancel_at_period_end, last_event_created_at, created_at, updated_at
FROM subscriptions
WHERE billing_account_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSubscriptionsForBillingAccount(ctx context.Context, billingAccountID pgtype.UUID) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsForBillingAccount, billingAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.BillingAccountID,
			&i.StripeSubscriptionID,
			&i.PriceKey,
			&i.Status,
			&i.CurrentPeriodEnd,
			&i.CancelAtPeriodEnd,
			&i.LastEventCreatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCheckoutSessionStatus = `-- name: UpdateCheckoutSessionStatus :execrows
UPDATE checkout_sessions
SET status = $2,
    updated_at = now()
WHERE stripe_checkout_session_id = $1
`

type UpdateCheckoutSessionStatusParams struct {
	StripeCheckoutSessionID string `db:"stripe_checkout_session_id" json:"stripe_checkout_session_id"`
	Status                  string `db:"status" json:"status"`
}

func (q *Queries) UpdateCheckoutSessionStatus(ctx context.Context, arg UpdateCheckoutSessionStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCheckoutSessionStatus, arg.StripeCheckoutSessionID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertEntitlement = `-- name: UpsertEntitlement :one
INSERT INTO entitlements (organization_id, feature_key, source, enabled, expires_at, subscription_id, one_time_purchase_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (organization_id, feature_key, source) DO UPDATE
SET enabled = EXCLUDED.enabled,
    expires_at = EXCLUDED.expires_at,
    subscription_id = EXCLUDED.subscription_id,
    one_time_purchase_id = EXCLUDED.one_time_purchase_id,
    updated_at = now()
RETURNING id, organization_id, feature_key, source, enabled, expires_at, subscription_id, one_time_purchase_id, created_at, updated_at
`

type UpsertEntitlementParams struct {
	OrganizationID    pgtype.UUID        `db:"organization_id" json:"organization_id"`
	FeatureKey        string             `db:"feature_key" json:"feature_key"`
	Source            string             `db:"source" json:"source"`
	Enabled           bool               `db:"enabled" json:"enabled"`
	ExpiresAt         pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	SubscriptionID    pgtype.UUID        `db:"subscription_id" json:"subscription_id"`
	OneTimePurchaseID pgtype.UUID        `db:"one_time_purchase_id" json:"one_time_purchase_id"`
}

func (q *Queries) UpsertEntitlement(ctx context.Context, arg UpsertEntitlementParams) (Entitlement, error) {
	row := q.db.QueryRow(ctx, upsertEntitlement,
		arg.OrganizationID,
		arg.FeatureKey,
		arg.Source,
		arg.Enabled,
		arg.ExpiresAt,
		arg.SubscriptionID,
		arg.OneTimePurchaseID,
	)
	var i Entitlement
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.FeatureKey,
		&i.Source,
		&i.Enabled,
		&i.ExpiresAt,
		&i.SubscriptionID,
		&i.OneTimePurchaseID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSubscription = `-- name: UpsertSubscription :one
INSERT INTO subscriptions (
    billing_account_id, stripe_subscription_id, price_key, status,
    current_period_end, cancel_at_period_end, last_event_created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (stripe_subscription_id) DO UPDATE
SET price_key = EXCLUDED.price_key,
    status = EXCLUDED.status,
    current_period_end = EXCLUDED.current_period_end,
    cancel_at_period_end = EXCLUDED.cancel_at_period_end,
    last_event_created_at = EXCLUDED.last_event_created_at,
    updated_at = now()
WHERE subscriptions.last_event_created_at IS NULL
   OR subscriptions.last_event_created_at < EXCLUDED.last_event_created_at
RETURNING id, billing_account_id, stripe_subscription_id, price_key, status,
          current_period_end, cancel_at_period_end, last_event_created_at, created_at, updated_at
`

type UpsertSubscriptionParams struct {
	BillingAccountID     pgtype.UUID        `db:"billing_account_id" json:"billing_account_id"`
	StripeSubscriptionID string             `db:"stripe_subscription_id" json:"stripe_subscription_id"`
	PriceKey             string             `db:"price_key" json:"price_key"`
	Status               string             `db:"status" json:"status"`
	CurrentPeriodEnd     pgtype.Timestamptz `db:"current_period_end" json:"current_period_end"`
	CancelAtPeriodEnd    bool               `db:"cancel_at_period_end" json:"cancel_at_period_end"`
	LastEventCreatedAt   pgtype.Timestamptz `db:"last_event_created_at" json:"last_event_created_at"`
}

// Monotonic guard: the ON CONFLICT DO UPDATE only fires when the incoming
// event is at least as new as the last one applied to this subscription, so
// an out-of-order (older) webhook delivery can never regress state. When the
// guard rejects the update, no row is returned (treat as a no-op, not an
// error).
func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, upsertSubscription,
		arg.BillingAccountID,
		arg.StripeSubscriptionID,
		arg.PriceKey,
		arg.Status,
		arg.CurrentPeriodEnd,
		arg.CancelAtPeriodEnd,
		arg.LastEventCreatedAt,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.BillingAccountID,
		&i.StripeSubscriptionID,
		&i.PriceKey,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.LastEventCreatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
