// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: otp.sql

package store

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeEmailOTPChallengeByID = `-- name: ConsumeEmailOTPChallengeByID :one
UPDATE email_otp_challenges
SET consumed_at = now()
WHERE id = $1
  AND consumed_at IS NULL
  AND expires_at > now()
RETURNING id, email
`

type ConsumeEmailOTPChallengeByIDRow struct {
	ID    pgtype.UUID `db:"id" json:"id"`
	Email string      `db:"email" json:"email"`
}

func (q *Queries) ConsumeEmailOTPChallengeByID(ctx context.Context, id pgtype.UUID) (ConsumeEmailOTPChallengeByIDRow, error) {
	row := q.db.QueryRow(ctx, consumeEmailOTPChallengeByID, id)
	var i ConsumeEmailOTPChallengeByIDRow
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}

const countRecentEmailOTPChallenges = `-- name: CountRecentEmailOTPChallenges :one
SELECT count(*)
FROM email_otp_challenges
WHERE email = $1 AND created_at > $2
`

type CountRecentEmailOTPChallengesParams struct {
	Email     string             `db:"email" json:"email"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) CountRecentEmailOTPChallenges(ctx context.Context, arg CountRecentEmailOTPChallengesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentEmailOTPChallenges, arg.Email, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentEmailOTPChallengesByIP = `-- name: CountRecentEmailOTPChallengesByIP :one
SELECT count(*)
FROM email_otp_challenges
WHERE ip_address = $1 AND created_at > $2
`

type CountRecentEmailOTPChallengesByIPParams struct {
	IpAddress *netip.Addr        `db:"ip_address" json:"ip_address"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) CountRecentEmailOTPChallengesByIP(ctx context.Context, arg CountRecentEmailOTPChallengesByIPParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentEmailOTPChallengesByIP, arg.IpAddress, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmailOTPChallenge = `-- name: CreateEmailOTPChallenge :one
INSERT INTO email_otp_challenges (email, purpose, code_digest, ip_address, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, purpose, expires_at, created_at
`

type CreateEmailOTPChallengeParams struct {
	Email      string             `db:"email" json:"email"`
	Purpose    string             `db:"purpose" json:"purpose"`
	CodeDigest []byte             `db:"code_digest" json:"code_digest"`
	IpAddress  *netip.Addr        `db:"ip_address" json:"ip_address"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

type CreateEmailOTPChallengeRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Email     string             `db:"email" json:"email"`
	Purpose   string             `db:"purpose" json:"purpose"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateEmailOTPChallenge(ctx context.Context, arg CreateEmailOTPChallengeParams) (CreateEmailOTPChallengeRow, error) {
	row := q.db.QueryRow(ctx, createEmailOTPChallenge,
		arg.Email,
		arg.Purpose,
		arg.CodeDigest,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i CreateEmailOTPChallengeRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Purpose,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const findActiveEmailOTPChallenge = `-- name: FindActiveEmailOTPChallenge :one
SELECT id, email, purpose, code_digest, attempt_count, max_attempts, expires_at
FROM email_otp_challenges
WHERE email = $1
  AND purpose = $2
  AND consumed_at IS NULL
  AND expires_at > now()
ORDER BY created_at DESC
LIMIT 1
`

type FindActiveEmailOTPChallengeParams struct {
	Email   string `db:"email" json:"email"`
	Purpose string `db:"purpose" json:"purpose"`
}

type FindActiveEmailOTPChallengeRow struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Email        string             `db:"email" json:"email"`
	Purpose      string             `db:"purpose" json:"purpose"`
	CodeDigest   []byte             `db:"code_digest" json:"code_digest"`
	AttemptCount int32              `db:"attempt_count" json:"attempt_count"`
	MaxAttempts  int32              `db:"max_attempts" json:"max_attempts"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) FindActiveEmailOTPChallenge(ctx context.Context, arg FindActiveEmailOTPChallengeParams) (FindActiveEmailOTPChallengeRow, error) {
	row := q.db.QueryRow(ctx, findActiveEmailOTPChallenge, arg.Email, arg.Purpose)
	var i FindActiveEmailOTPChallengeRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Purpose,
		&i.CodeDigest,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.ExpiresAt,
	)
	return i, err
}

const incrementEmailOTPAttempt = `-- name: IncrementEmailOTPAttempt :one
UPDATE email_otp_challenges
SET attempt_count = attempt_count + 1
WHERE id = $1
  AND consumed_at IS NULL
  AND expires_at > now()
  AND attempt_count < max_attempts
RETURNING id, attempt_count, max_attempts
`

type IncrementEmailOTPAttemptRow struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	AttemptCount int32       `db:"attempt_count" json:"attempt_count"`
	MaxAttempts  int32       `db:"max_attempts" json:"max_attempts"`
}

func (q *Queries) IncrementEmailOTPAttempt(ctx context.Context, id pgtype.UUID) (IncrementEmailOTPAttemptRow, error) {
	row := q.db.QueryRow(ctx, incrementEmailOTPAttempt, id)
	var i IncrementEmailOTPAttemptRow
	err := row.Scan(&i.ID, &i.AttemptCount, &i.MaxAttempts)
	return i, err
}
