// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimOutboxEvents = `-- name: ClaimOutboxEvents :many
WITH candidates AS (
    SELECT id
    FROM outbox_events
    WHERE processed_at IS NULL
      AND available_at <= now()
      AND (claimed_at IS NULL OR claimed_at < now() - $2::interval)
    ORDER BY available_at, created_at
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
UPDATE outbox_events AS event
SET claimed_at = now(), claim_token = $1::uuid, attempts = attempts + 1
FROM candidates
WHERE event.id = candidates.id
RETURNING event.id, event.topic, event.aggregate_type, event.aggregate_id, event.payload, event.idempotency_key,
          event.available_at, event.claimed_at, event.claim_token, event.attempts, event.processed_at, event.last_error, event.created_at
`

type ClaimOutboxEventsParams struct {
	ClaimToken   pgtype.UUID     `db:"claim_token" json:"claim_token"`
	ClaimTimeout pgtype.Interval `db:"claim_timeout" json:"claim_timeout"`
	BatchSize    int32           `db:"batch_size" json:"batch_size"`
}

func (q *Queries) ClaimOutboxEvents(ctx context.Context, arg ClaimOutboxEventsParams) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, claimOutboxEvents, arg.ClaimToken, arg.ClaimTimeout, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.AggregateType,
			&i.AggregateID,
			&i.Payload,
			&i.IdempotencyKey,
			&i.AvailableAt,
			&i.ClaimedAt,
			&i.ClaimToken,
			&i.Attempts,
			&i.ProcessedAt,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeDeliveryAttempt = `-- name: CompleteDeliveryAttempt :execrows
UPDATE delivery_attempts
SET status = $2, provider_response = $3, error_message = $4, completed_at = now()
WHERE id = $1 AND status = 'claimed'
`

type CompleteDeliveryAttemptParams struct {
	ID               pgtype.UUID `db:"id" json:"id"`
	Status           string      `db:"status" json:"status"`
	ProviderResponse *string     `db:"provider_response" json:"provider_response"`
	ErrorMessage     *string     `db:"error_message" json:"error_message"`
}

func (q *Queries) CompleteDeliveryAttempt(ctx context.Context, arg CompleteDeliveryAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeDeliveryAttempt,
		arg.ID,
		arg.Status,
		arg.ProviderResponse,
		arg.ErrorMessage,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createDeliveryAttempt = `-- name: CreateDeliveryAttempt :one
INSERT INTO delivery_attempts (delivery_message_id, attempt_number, status)
VALUES ($1, $2, $3)
RETURNING id, delivery_message_id, attempt_number, status, provider_response, error_message, started_at, completed_at
`

type CreateDeliveryAttemptParams struct {
	DeliveryMessageID pgtype.UUID `db:"delivery_message_id" json:"delivery_message_id"`
	AttemptNumber     int32       `db:"attempt_number" json:"attempt_number"`
	Status            string      `db:"status" json:"status"`
}

func (q *Queries) CreateDeliveryAttempt(ctx context.Context, arg CreateDeliveryAttemptParams) (DeliveryAttempt, error) {
	row := q.db.QueryRow(ctx, createDeliveryAttempt, arg.DeliveryMessageID, arg.AttemptNumber, arg.Status)
	var i DeliveryAttempt
	err := row.Scan(
		&i.ID,
		&i.DeliveryMessageID,
		&i.AttemptNumber,
		&i.Status,
		&i.ProviderResponse,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createDeliveryMessage = `-- name: CreateDeliveryMessage :one
INSERT INTO delivery_messages (notification_intent_id, outbox_event_id, channel, recipient, subject, text_body, html_body, idempotency_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, notification_intent_id, outbox_event_id, channel, recipient, subject, text_body, html_body, idempotency_key, created_at
`

type CreateDeliveryMessageParams struct {
	NotificationIntentID pgtype.UUID `db:"notification_intent_id" json:"notification_intent_id"`
	OutboxEventID        pgtype.UUID `db:"outbox_event_id" json:"outbox_event_id"`
	Channel              string      `db:"channel" json:"channel"`
	Recipient            string      `db:"recipient" json:"recipient"`
	Subject              string      `db:"subject" json:"subject"`
	TextBody             string      `db:"text_body" json:"text_body"`
	HtmlBody             string      `db:"html_body" json:"html_body"`
	IdempotencyKey       string      `db:"idempotency_key" json:"idempotency_key"`
}

func (q *Queries) CreateDeliveryMessage(ctx context.Context, arg CreateDeliveryMessageParams) (DeliveryMessage, error) {
	row := q.db.QueryRow(ctx, createDeliveryMessage,
		arg.NotificationIntentID,
		arg.OutboxEventID,
		arg.Channel,
		arg.Recipient,
		arg.Subject,
		arg.TextBody,
		arg.HtmlBody,
		arg.IdempotencyKey,
	)
	var i DeliveryMessage
	err := row.Scan(
		&i.ID,
		&i.NotificationIntentID,
		&i.OutboxEventID,
		&i.Channel,
		&i.Recipient,
		&i.Subject,
		&i.TextBody,
		&i.HtmlBody,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const createNotificationIntent = `-- name: CreateNotificationIntent :one
INSERT INTO notification_intents (recipient_user_id, kind, payload)
VALUES ($1, $2, $3)
RETURNING id, recipient_user_id, kind, payload, created_at
`

type CreateNotificationIntentParams struct {
	RecipientUserID pgtype.UUID `db:"recipient_user_id" json:"recipient_user_id"`
	Kind            string      `db:"kind" json:"kind"`
	Payload         []byte      `db:"payload" json:"payload"`
}

func (q *Queries) CreateNotificationIntent(ctx context.Context, arg CreateNotificationIntentParams) (NotificationIntent, error) {
	row := q.db.QueryRow(ctx, createNotificationIntent, arg.RecipientUserID, arg.Kind, arg.Payload)
	var i NotificationIntent
	err := row.Scan(
		&i.ID,
		&i.RecipientUserID,
		&i.Kind,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox_events (topic, aggregate_type, aggregate_id, payload, idempotency_key, available_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, topic, aggregate_type, aggregate_id, payload, idempotency_key, available_at, claimed_at, claim_token, attempts, processed_at, last_error, created_at
`

type CreateOutboxEventParams struct {
	Topic          string             `db:"topic" json:"topic"`
	AggregateType  string             `db:"aggregate_type" json:"aggregate_type"`
	AggregateID    pgtype.UUID        `db:"aggregate_id" json:"aggregate_id"`
	Payload        []byte             `db:"payload" json:"payload"`
	IdempotencyKey string             `db:"idempotency_key" json:"idempotency_key"`
	AvailableAt    pgtype.Timestamptz `db:"available_at" json:"available_at"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent,
		arg.Topic,
		arg.AggregateType,
		arg.AggregateID,
		arg.Payload,
		arg.IdempotencyKey,
		arg.AvailableAt,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.AggregateType,
		&i.AggregateID,
		&i.Payload,
		&i.IdempotencyKey,
		&i.AvailableAt,
		&i.ClaimedAt,
		&i.ClaimToken,
		&i.Attempts,
		&i.ProcessedAt,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const getDeliveryMessageByOutboxEvent = `-- name: GetDeliveryMessageByOutboxEvent :one
SELECT id, notification_intent_id, outbox_event_id, channel, recipient, subject, text_body, html_body, idempotency_key, created_at
FROM delivery_messages
WHERE outbox_event_id = $1
`

func (q *Queries) GetDeliveryMessageByOutboxEvent(ctx context.Context, outboxEventID pgtype.UUID) (DeliveryMessage, error) {
	row := q.db.QueryRow(ctx, getDeliveryMessageByOutboxEvent, outboxEventID)
	var i DeliveryMessage
	err := row.Scan(
		&i.ID,
		&i.NotificationIntentID,
		&i.OutboxEventID,
		&i.Channel,
		&i.Recipient,
		&i.Subject,
		&i.TextBody,
		&i.HtmlBody,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const markOutboxEventProcessed = `-- name: MarkOutboxEventProcessed :execrows
UPDATE outbox_events
SET processed_at = now(), claimed_at = NULL, claim_token = NULL, last_error = NULL
WHERE id = $1 AND claim_token = $2 AND processed_at IS NULL
`

type MarkOutboxEventProcessedParams struct {
	ID         pgtype.UUID `db:"id" json:"id"`
	ClaimToken pgtype.UUID `db:"claim_token" json:"claim_token"`
}

func (q *Queries) MarkOutboxEventProcessed(ctx context.Context, arg MarkOutboxEventProcessedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxEventProcessed, arg.ID, arg.ClaimToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryOutboxEvent = `-- name: RetryOutboxEvent :execrows
UPDATE outbox_events
SET available_at = $3, claimed_at = NULL, claim_token = NULL, last_error = $4
WHERE id = $1 AND claim_token = $2 AND processed_at IS NULL
`

type RetryOutboxEventParams struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	ClaimToken  pgtype.UUID        `db:"claim_token" json:"claim_token"`
	AvailableAt pgtype.Timestamptz `db:"available_at" json:"available_at"`
	LastError   *string            `db:"last_error" json:"last_error"`
}

func (q *Queries) RetryOutboxEvent(ctx context.Context, arg RetryOutboxEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryOutboxEvent,
		arg.ID,
		arg.ClaimToken,
		arg.AvailableAt,
		arg.LastError,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
