// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptInvitation(ctx context.Context, id pgtype.UUID) (OrganizationInvitation, error)
	ActivateTOTPFactor(ctx context.Context, arg ActivateTOTPFactorParams) (int64, error)
	ClaimOutboxEvents(ctx context.Context, arg ClaimOutboxEventsParams) ([]OutboxEvent, error)
	CompleteDeliveryAttempt(ctx context.Context, arg CompleteDeliveryAttemptParams) (int64, error)
	ConsumeEmailOTPChallengeByID(ctx context.Context, id pgtype.UUID) (ConsumeEmailOTPChallengeByIDRow, error)
	ConsumeMFAChallenge(ctx context.Context, id pgtype.UUID) (ConsumeMFAChallengeRow, error)
	ConsumeOAuthAuthorizationState(ctx context.Context, arg ConsumeOAuthAuthorizationStateParams) (ConsumeOAuthAuthorizationStateRow, error)
	ConsumeOneTimeToken(ctx context.Context, arg ConsumeOneTimeTokenParams) (ConsumeOneTimeTokenRow, error)
	ConsumeRefreshSession(ctx context.Context, tokenDigest []byte) (ConsumeRefreshSessionRow, error)
	ConsumeTOTPRecoveryCode(ctx context.Context, arg ConsumeTOTPRecoveryCodeParams) (pgtype.UUID, error)
	ConsumeWebAuthnChallenge(ctx context.Context, arg ConsumeWebAuthnChallengeParams) (ConsumeWebAuthnChallengeRow, error)
	CountAnnouncements(ctx context.Context, arg CountAnnouncementsParams) (int64, error)
	CountOrganizationOwners(ctx context.Context, organizationID pgtype.UUID) (int64, error)
	CountRecentEmailOTPChallenges(ctx context.Context, arg CountRecentEmailOTPChallengesParams) (int64, error)
	CountRecentEmailOTPChallengesByIP(ctx context.Context, arg CountRecentEmailOTPChallengesByIPParams) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error)
	CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (CreateAnnouncementRow, error)
	CreateBillingAccount(ctx context.Context, arg CreateBillingAccountParams) (BillingAccount, error)
	CreateCheckoutSession(ctx context.Context, arg CreateCheckoutSessionParams) (CheckoutSession, error)
	CreateDeliveryAttempt(ctx context.Context, arg CreateDeliveryAttemptParams) (DeliveryAttempt, error)
	CreateDeliveryMessage(ctx context.Context, arg CreateDeliveryMessageParams) (DeliveryMessage, error)
	CreateEmailOTPChallenge(ctx context.Context, arg CreateEmailOTPChallengeParams) (CreateEmailOTPChallengeRow, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (OrganizationInvitation, error)
	CreateMFAChallenge(ctx context.Context, arg CreateMFAChallengeParams) (CreateMFAChallengeRow, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (OrganizationMembership, error)
	CreateNotificationIntent(ctx context.Context, arg CreateNotificationIntentParams) (NotificationIntent, error)
	CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error)
	CreateOAuthAuthorizationState(ctx context.Context, arg CreateOAuthAuthorizationStateParams) (CreateOAuthAuthorizationStateRow, error)
	CreateOneTimeToken(ctx context.Context, arg CreateOneTimeTokenParams) (OneTimeToken, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error)
	CreateRefreshSession(ctx context.Context, arg CreateRefreshSessionParams) (RefreshSession, error)
	CreateRefreshTokenFamily(ctx context.Context, userID pgtype.UUID) (RefreshTokenFamily, error)
	CreateTOTPFactor(ctx context.Context, arg CreateTOTPFactorParams) (TotpFactor, error)
	CreateTOTPRecoveryCode(ctx context.Context, arg CreateTOTPRecoveryCodeParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWebAuthnChallenge(ctx context.Context, arg CreateWebAuthnChallengeParams) (CreateWebAuthnChallengeRow, error)
	CreateWebAuthnCredential(ctx context.Context, arg CreateWebAuthnCredentialParams) (CreateWebAuthnCredentialRow, error)
	DeleteAnnouncement(ctx context.Context, arg DeleteAnnouncementParams) (int64, error)
	DeleteCasbinRule(ctx context.Context, arg DeleteCasbinRuleParams) (int64, error)
	DeleteCasbinRulesByDomain(ctx context.Context, v1 string) (int64, error)
	DeleteCasbinRulesByPtype(ctx context.Context, ptype string) (int64, error)
	DeleteMembership(ctx context.Context, arg DeleteMembershipParams) (int64, error)
	DeleteOrganization(ctx context.Context, id pgtype.UUID) (int64, error)
	DeletePendingTOTPFactorsForUser(ctx context.Context, userID pgtype.UUID) (int64, error)
	FindActiveEmailOTPChallenge(ctx context.Context, arg FindActiveEmailOTPChallengeParams) (FindActiveEmailOTPChallengeRow, error)
	FindOAuthAccount(ctx context.Context, arg FindOAuthAccountParams) (OauthAccount, error)
	FindRefreshSession(ctx context.Context, tokenDigest []byte) (FindRefreshSessionRow, error)
	GetActiveAPIKeyByDigest(ctx context.Context, secretDigest []byte) (GetActiveAPIKeyByDigestRow, error)
	GetActiveMFAChallenge(ctx context.Context, id pgtype.UUID) (GetActiveMFAChallengeRow, error)
	GetAnnouncement(ctx context.Context, arg GetAnnouncementParams) (GetAnnouncementRow, error)
	GetBillingAccountByOrganization(ctx context.Context, organizationID pgtype.UUID) (BillingAccount, error)
	GetBillingAccountByStripeCustomerID(ctx context.Context, stripeCustomerID string) (BillingAccount, error)
	GetCheckoutSessionByStripeID(ctx context.Context, stripeCheckoutSessionID string) (CheckoutSession, error)
	GetDeliveryMessageByOutboxEvent(ctx context.Context, outboxEventID pgtype.UUID) (DeliveryMessage, error)
	GetInvitationByDigest(ctx context.Context, tokenDigest []byte) (OrganizationInvitation, error)
	GetInvitationByID(ctx context.Context, id pgtype.UUID) (OrganizationInvitation, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (OrganizationMembership, error)
	GetOrganizationByID(ctx context.Context, id pgtype.UUID) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	GetOutboxEventByID(ctx context.Context, id pgtype.UUID) (OutboxEvent, error)
	GetSubscriptionByStripeID(ctx context.Context, stripeSubscriptionID string) (Subscription, error)
	GetTOTPFactorByID(ctx context.Context, id pgtype.UUID) (TotpFactor, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetVerifiedTOTPFactorForUser(ctx context.Context, userID pgtype.UUID) (TotpFactor, error)
	GetWebAuthnCredentialByCredentialID(ctx context.Context, credentialID []byte) (WebauthnCredential, error)
	HasEntitlement(ctx context.Context, arg HasEntitlementParams) (bool, error)
	IncrementEmailOTPAttempt(ctx context.Context, id pgtype.UUID) (IncrementEmailOTPAttemptRow, error)
	InsertCasbinRule(ctx context.Context, arg InsertCasbinRuleParams) (CasbinRule, error)
	// ON CONFLICT DO NOTHING makes re-delivery of the same checkout session's
	// completion event idempotent at the row level, independent of the
	// stripe_webhook_events dedup (defense in depth).
	InsertOneTimePurchase(ctx context.Context, arg InsertOneTimePurchaseParams) (OneTimePurchase, error)
	// Single-statement, constraint-based idempotency check: ON CONFLICT DO
	// NOTHING means a duplicate delivery of the same Stripe event ID returns no
	// row (not an error), which the caller treats as "already processed".
	InsertWebhookEvent(ctx context.Context, arg InsertWebhookEventParams) (StripeWebhookEvent, error)
	ListAPIKeysForUser(ctx context.Context, userID pgtype.UUID) ([]ListAPIKeysForUserRow, error)
	ListAnnouncements(ctx context.Context, arg ListAnnouncementsParams) ([]ListAnnouncementsRow, error)
	ListCasbinRules(ctx context.Context) ([]CasbinRule, error)
	ListDeliveryAttemptsByMessage(ctx context.Context, deliveryMessageID pgtype.UUID) ([]DeliveryAttempt, error)
	ListEntitlementsForOrganization(ctx context.Context, organizationID pgtype.UUID) ([]Entitlement, error)
	ListInvitations(ctx context.Context, organizationID pgtype.UUID) ([]OrganizationInvitation, error)
	ListMemberships(ctx context.Context, organizationID pgtype.UUID) ([]ListMembershipsRow, error)
	ListOAuthAccountsForUser(ctx context.Context, userID pgtype.UUID) ([]OauthAccount, error)
	ListOneTimePurchasesForBillingAccount(ctx context.Context, billingAccountID pgtype.UUID) ([]OneTimePurchase, error)
	ListOrganizationsForUser(ctx context.Context, userID pgtype.UUID) ([]ListOrganizationsForUserRow, error)
	ListRefreshSessionsForUser(ctx context.Context, userID pgtype.UUID) ([]ListRefreshSessionsForUserRow, error)
	ListSubscriptionsForBillingAccount(ctx context.Context, billingAccountID pgtype.UUID) ([]Subscription, error)
	ListWebAuthnCredentialsForUser(ctx context.Context, userID pgtype.UUID) ([]WebauthnCredential, error)
	MarkOutboxEventProcessed(ctx context.Context, arg MarkOutboxEventProcessedParams) (int64, error)
	MarkUserEmailVerified(ctx context.Context, id pgtype.UUID) (int64, error)
	RetryOutboxEvent(ctx context.Context, arg RetryOutboxEventParams) (int64, error)
	RevokeAPIKeyForUser(ctx context.Context, arg RevokeAPIKeyForUserParams) (int64, error)
	RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (int64, error)
	RevokeRefreshFamiliesForUser(ctx context.Context, arg RevokeRefreshFamiliesForUserParams) (int64, error)
	RevokeRefreshFamily(ctx context.Context, arg RevokeRefreshFamilyParams) (int64, error)
	RevokeRefreshSessionForUser(ctx context.Context, arg RevokeRefreshSessionForUserParams) (int64, error)
	UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) (UpdateAnnouncementRow, error)
	UpdateCheckoutSessionStatus(ctx context.Context, arg UpdateCheckoutSessionStatusParams) (int64, error)
	UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (OrganizationMembership, error)
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error)
	UpdateWebAuthnCredentialSignCount(ctx context.Context, arg UpdateWebAuthnCredentialSignCountParams) (int64, error)
	UpsertEntitlement(ctx context.Context, arg UpsertEntitlementParams) (Entitlement, error)
	// Monotonic guard: the ON CONFLICT DO UPDATE only fires when the incoming
	// event is at least as new as the last one applied to this subscription, so
	// an out-of-order (older) webhook delivery can never regress state. When the
	// guard rejects the update, no row is returned (treat as a no-op, not an
	// error).
	UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (Subscription, error)
}

var _ Querier = (*Queries)(nil)
