// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: system_settings.sql

package store

import (
	"context"
)

const deleteSystemSetting = `-- name: DeleteSystemSetting :execrows
DELETE FROM system_settings
WHERE key = $1
`

func (q *Queries) DeleteSystemSetting(ctx context.Context, key string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSystemSetting, key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSystemSetting = `-- name: GetSystemSetting :one
SELECT key, value, description, updated_at
FROM system_settings
WHERE key = $1
`

func (q *Queries) GetSystemSetting(ctx context.Context, key string) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, getSystemSetting, key)
	var i SystemSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Description,
		&i.UpdatedAt,
	)
	return i, err
}

const listSystemSettings = `-- name: ListSystemSettings :many
SELECT key, value, description, updated_at
FROM system_settings
ORDER BY key
`

func (q *Queries) ListSystemSettings(ctx context.Context) ([]SystemSetting, error) {
	rows, err := q.db.Query(ctx, listSystemSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemSetting{}
	for rows.Next() {
		var i SystemSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Description,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSystemSetting = `-- name: UpsertSystemSetting :one
INSERT INTO system_settings (key, value, description)
VALUES ($1, $2, $3)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value,
    description = EXCLUDED.description,
    updated_at = now()
RETURNING key, value, description, updated_at
`

type UpsertSystemSettingParams struct {
	Key         string `db:"key" json:"key"`
	Value       []byte `db:"value" json:"value"`
	Description string `db:"description" json:"description"`
}

func (q *Queries) UpsertSystemSetting(ctx context.Context, arg UpsertSystemSettingParams) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, upsertSystemSetting, arg.Key, arg.Value, arg.Description)
	var i SystemSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Description,
		&i.UpdatedAt,
	)
	return i, err
}
