// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: totp.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateTOTPFactor = `-- name: ActivateTOTPFactor :execrows
UPDATE totp_factors
SET status = 'verified', verified_at = now()
WHERE id = $1 AND user_id = $2 AND status = 'pending'
`

type ActivateTOTPFactorParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) ActivateTOTPFactor(ctx context.Context, arg ActivateTOTPFactorParams) (int64, error) {
	result, err := q.db.Exec(ctx, activateTOTPFactor, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeMFAChallenge = `-- name: ConsumeMFAChallenge :one
UPDATE mfa_challenges
SET consumed_at = now()
WHERE id = $1
  AND consumed_at IS NULL
  AND expires_at > now()
RETURNING id, user_id, factor_id
`

type ConsumeMFAChallengeRow struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
	FactorID pgtype.UUID `db:"factor_id" json:"factor_id"`
}

func (q *Queries) ConsumeMFAChallenge(ctx context.Context, id pgtype.UUID) (ConsumeMFAChallengeRow, error) {
	row := q.db.QueryRow(ctx, consumeMFAChallenge, id)
	var i ConsumeMFAChallengeRow
	err := row.Scan(&i.ID, &i.UserID, &i.FactorID)
	return i, err
}

const consumeTOTPRecoveryCode = `-- name: ConsumeTOTPRecoveryCode :one
UPDATE totp_recovery_codes
SET consumed_at = now()
WHERE factor_id = $1
  AND code_digest = $2
  AND consumed_at IS NULL
RETURNING id
`

type ConsumeTOTPRecoveryCodeParams struct {
	FactorID   pgtype.UUID `db:"factor_id" json:"factor_id"`
	CodeDigest []byte      `db:"code_digest" json:"code_digest"`
}

func (q *Queries) ConsumeTOTPRecoveryCode(ctx context.Context, arg ConsumeTOTPRecoveryCodeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, consumeTOTPRecoveryCode, arg.FactorID, arg.CodeDigest)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createMFAChallenge = `-- name: CreateMFAChallenge :one
INSERT INTO mfa_challenges (user_id, factor_id, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, factor_id, expires_at, created_at
`

type CreateMFAChallengeParams struct {
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	FactorID  pgtype.UUID        `db:"factor_id" json:"factor_id"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

type CreateMFAChallengeRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	FactorID  pgtype.UUID        `db:"factor_id" json:"factor_id"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateMFAChallenge(ctx context.Context, arg CreateMFAChallengeParams) (CreateMFAChallengeRow, error) {
	row := q.db.QueryRow(ctx, createMFAChallenge, arg.UserID, arg.FactorID, arg.ExpiresAt)
	var i CreateMFAChallengeRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FactorID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createTOTPFactor = `-- name: CreateTOTPFactor :one
INSERT INTO totp_factors (user_id, secret_ciphertext, secret_nonce, status)
VALUES ($1, $2, $3, 'pending')
RETURNING id, user_id, secret_ciphertext, secret_nonce, status, created_at, verified_at
`

type CreateTOTPFactorParams struct {
	UserID           pgtype.UUID `db:"user_id" json:"user_id"`
	SecretCiphertext []byte      `db:"secret_ciphertext" json:"secret_ciphertext"`
	SecretNonce      []byte      `db:"secret_nonce" json:"secret_nonce"`
}

func (q *Queries) CreateTOTPFactor(ctx context.Context, arg CreateTOTPFactorParams) (TotpFactor, error) {
	row := q.db.QueryRow(ctx, createTOTPFactor, arg.UserID, arg.SecretCiphertext, arg.SecretNonce)
	var i TotpFactor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SecretCiphertext,
		&i.SecretNonce,
		&i.Status,
		&i.CreatedAt,
		&i.VerifiedAt,
	)
	return i, err
}

const createTOTPRecoveryCode = `-- name: CreateTOTPRecoveryCode :exec
INSERT INTO totp_recovery_codes (factor_id, code_digest)
VALUES ($1, $2)
`

type CreateTOTPRecoveryCodeParams struct {
	FactorID   pgtype.UUID `db:"factor_id" json:"factor_id"`
	CodeDigest []byte      `db:"code_digest" json:"code_digest"`
}

func (q *Queries) CreateTOTPRecoveryCode(ctx context.Context, arg CreateTOTPRecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, createTOTPRecoveryCode, arg.FactorID, arg.CodeDigest)
	return err
}

const deletePendingTOTPFactorsForUser = `-- name: DeletePendingTOTPFactorsForUser :execrows
DELETE FROM totp_factors
WHERE user_id = $1 AND status = 'pending'
`

func (q *Queries) DeletePendingTOTPFactorsForUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePendingTOTPFactorsForUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveMFAChallenge = `-- name: GetActiveMFAChallenge :one
SELECT id, user_id, factor_id, expires_at
FROM mfa_challenges
WHERE id = $1
  AND consumed_at IS NULL
  AND expires_at > now()
`

type GetActiveMFAChallengeRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	FactorID  pgtype.UUID        `db:"factor_id" json:"factor_id"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) GetActiveMFAChallenge(ctx context.Context, id pgtype.UUID) (GetActiveMFAChallengeRow, error) {
	row := q.db.QueryRow(ctx, getActiveMFAChallenge, id)
	var i GetActiveMFAChallengeRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FactorID,
		&i.ExpiresAt,
	)
	return i, err
}

const getTOTPFactorByID = `-- name: GetTOTPFactorByID :one
SELECT id, user_id, secret_ciphertext, secret_nonce, status, created_at, verified_at
FROM totp_factors
WHERE id = $1
`

func (q *Queries) GetTOTPFactorByID(ctx context.Context, id pgtype.UUID) (TotpFactor, error) {
	row := q.db.QueryRow(ctx, getTOTPFactorByID, id)
	var i TotpFactor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SecretCiphertext,
		&i.SecretNonce,
		&i.Status,
		&i.CreatedAt,
		&i.VerifiedAt,
	)
	return i, err
}

const getVerifiedTOTPFactorForUser = `-- name: GetVerifiedTOTPFactorForUser :one
SELECT id, user_id, secret_ciphertext, secret_nonce, status, created_at, verified_at
FROM totp_factors
WHERE user_id = $1 AND status = 'verified'
`

func (q *Queries) GetVerifiedTOTPFactorForUser(ctx context.Context, userID pgtype.UUID) (TotpFactor, error) {
	row := q.db.QueryRow(ctx, getVerifiedTOTPFactorForUser, userID)
	var i TotpFactor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SecretCiphertext,
		&i.SecretNonce,
		&i.Status,
		&i.CreatedAt,
		&i.VerifiedAt,
	)
	return i, err
}
