// Code generated by ogen, DO NOT EDIT.

package billingapi

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateCheckoutSessionOperation OperationName = "CreateCheckoutSession"
	CreatePortalSessionOperation   OperationName = "CreatePortalSession"
	GetBillingSummaryOperation     OperationName = "GetBillingSummary"
)
