// Code generated by ogen, DO NOT EDIT.

package billingapi

import (
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

// Ref: #/components/schemas/ApiError
type ApiError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ApiError) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ApiError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ApiError) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ApiError) SetMessage(val string) {
	s.Message = val
}

// Ref: #/components/schemas/BillingSummary
type BillingSummary struct {
	OrganizationId        uuid.UUID              `json:"organizationId"`
	HasActiveSubscription bool                   `json:"hasActiveSubscription"`
	Subscription          OptSubscriptionSummary `json:"subscription"`
	Entitlements          []EntitlementSummary   `json:"entitlements"`
}

// GetOrganizationId returns the value of OrganizationId.
func (s *BillingSummary) GetOrganizationId() uuid.UUID {
	return s.OrganizationId
}

// GetHasActiveSubscription returns the value of HasActiveSubscription.
func (s *BillingSummary) GetHasActiveSubscription() bool {
	return s.HasActiveSubscription
}

// GetSubscription returns the value of Subscription.
func (s *BillingSummary) GetSubscription() OptSubscriptionSummary {
	return s.Subscription
}

// GetEntitlements returns the value of Entitlements.
func (s *BillingSummary) GetEntitlements() []EntitlementSummary {
	return s.Entitlements
}

// SetOrganizationId sets the value of OrganizationId.
func (s *BillingSummary) SetOrganizationId(val uuid.UUID) {
	s.OrganizationId = val
}

// SetHasActiveSubscription sets the value of HasActiveSubscription.
func (s *BillingSummary) SetHasActiveSubscription(val bool) {
	s.HasActiveSubscription = val
}

// SetSubscription sets the value of Subscription.
func (s *BillingSummary) SetSubscription(val OptSubscriptionSummary) {
	s.Subscription = val
}

// SetEntitlements sets the value of Entitlements.
func (s *BillingSummary) SetEntitlements(val []EntitlementSummary) {
	s.Entitlements = val
}

func (*BillingSummary) getBillingSummaryRes() {}

// Ref: #/components/schemas/CheckoutSessionResponse
type CheckoutSessionResponse struct {
	ID  uuid.UUID `json:"id"`
	URL string    `json:"url"`
}

// GetID returns the value of ID.
func (s *CheckoutSessionResponse) GetID() uuid.UUID {
	return s.ID
}

// GetURL returns the value of URL.
func (s *CheckoutSessionResponse) GetURL() string {
	return s.URL
}

// SetID sets the value of ID.
func (s *CheckoutSessionResponse) SetID(val uuid.UUID) {
	s.ID = val
}

// SetURL sets the value of URL.
func (s *CheckoutSessionResponse) SetURL(val string) {
	s.URL = val
}

func (*CheckoutSessionResponse) createCheckoutSessionRes() {}

type CreateCheckoutSessionBadRequest ApiError

func (*CreateCheckoutSessionBadRequest) createCheckoutSessionRes() {}

type CreateCheckoutSessionForbidden ApiError

func (*CreateCheckoutSessionForbidden) createCheckoutSessionRes() {}

// Ref: #/components/schemas/CreateCheckoutSessionInput
type CreateCheckoutSessionInput struct {
	PriceKey string `json:"priceKey"`
}

// GetPriceKey returns the value of PriceKey.
func (s *CreateCheckoutSessionInput) GetPriceKey() string {
	return s.PriceKey
}

// SetPriceKey sets the value of PriceKey.
func (s *CreateCheckoutSessionInput) SetPriceKey(val string) {
	s.PriceKey = val
}

type CreateCheckoutSessionNotFound ApiError

func (*CreateCheckoutSessionNotFound) createCheckoutSessionRes() {}

type CreateCheckoutSessionUnauthorized ApiError

func (*CreateCheckoutSessionUnauthorized) createCheckoutSessionRes() {}

type CreatePortalSessionForbidden ApiError

func (*CreatePortalSessionForbidden) createPortalSessionRes() {}

type CreatePortalSessionNotFound ApiError

func (*CreatePortalSessionNotFound) createPortalSessionRes() {}

type CreatePortalSessionUnauthorized ApiError

func (*CreatePortalSessionUnauthorized) createPortalSessionRes() {}

// Ref: #/components/schemas/EntitlementSummary
type EntitlementSummary struct {
	FeatureKey string      `json:"featureKey"`
	Enabled    bool        `json:"enabled"`
	ExpiresAt  OptDateTime `json:"expiresAt"`
}

// GetFeatureKey returns the value of FeatureKey.
func (s *EntitlementSummary) GetFeatureKey() string {
	return s.FeatureKey
}

// GetEnabled returns the value of Enabled.
func (s *EntitlementSummary) GetEnabled() bool {
	return s.Enabled
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *EntitlementSummary) GetExpiresAt() OptDateTime {
	return s.ExpiresAt
}

// SetFeatureKey sets the value of FeatureKey.
func (s *EntitlementSummary) SetFeatureKey(val string) {
	s.FeatureKey = val
}

// SetEnabled sets the value of Enabled.
func (s *EntitlementSummary) SetEnabled(val bool) {
	s.Enabled = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *EntitlementSummary) SetExpiresAt(val OptDateTime) {
	s.ExpiresAt = val
}

type GetBillingSummaryForbidden ApiError

func (*GetBillingSummaryForbidden) getBillingSummaryRes() {}

type GetBillingSummaryNotFound ApiError

func (*GetBillingSummaryNotFound) getBillingSummaryRes() {}

type GetBillingSummaryUnauthorized ApiError

func (*GetBillingSummaryUnauthorized) getBillingSummaryRes() {}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSubscriptionSummary returns new OptSubscriptionSummary with value set to v.
func NewOptSubscriptionSummary(v SubscriptionSummary) OptSubscriptionSummary {
	return OptSubscriptionSummary{
		Value: v,
		Set:   true,
	}
}

// OptSubscriptionSummary is optional SubscriptionSummary.
type OptSubscriptionSummary struct {
	Value SubscriptionSummary
	Set   bool
}

// IsSet returns true if OptSubscriptionSummary was set.
func (o OptSubscriptionSummary) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSubscriptionSummary) Reset() {
	var v SubscriptionSummary
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSubscriptionSummary) SetTo(v SubscriptionSummary) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSubscriptionSummary) Get() (v SubscriptionSummary, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSubscriptionSummary) Or(d SubscriptionSummary) SubscriptionSummary {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/PortalSessionResponse
type PortalSessionResponse struct {
	URL string `json:"url"`
}

// GetURL returns the value of URL.
func (s *PortalSessionResponse) GetURL() string {
	return s.URL
}

// SetURL sets the value of URL.
func (s *PortalSessionResponse) SetURL(val string) {
	s.URL = val
}

func (*PortalSessionResponse) createPortalSessionRes() {}

// Ref: #/components/schemas/SubscriptionStatus
type SubscriptionStatus string

const (
	SubscriptionStatusActive            SubscriptionStatus = "active"
	SubscriptionStatusTrialing          SubscriptionStatus = "trialing"
	SubscriptionStatusPastDue           SubscriptionStatus = "past_due"
	SubscriptionStatusCanceled          SubscriptionStatus = "canceled"
	SubscriptionStatusIncomplete        SubscriptionStatus = "incomplete"
	SubscriptionStatusIncompleteExpired SubscriptionStatus = "incomplete_expired"
	SubscriptionStatusUnpaid            SubscriptionStatus = "unpaid"
	SubscriptionStatusPaused            SubscriptionStatus = "paused"
)

// AllValues returns all SubscriptionStatus values.
func (SubscriptionStatus) AllValues() []SubscriptionStatus {
	return []SubscriptionStatus{
		SubscriptionStatusActive,
		SubscriptionStatusTrialing,
		SubscriptionStatusPastDue,
		SubscriptionStatusCanceled,
		SubscriptionStatusIncomplete,
		SubscriptionStatusIncompleteExpired,
		SubscriptionStatusUnpaid,
		SubscriptionStatusPaused,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SubscriptionStatus) MarshalText() ([]byte, error) {
	switch s {
	case SubscriptionStatusActive:
		return []byte(s), nil
	case SubscriptionStatusTrialing:
		return []byte(s), nil
	case SubscriptionStatusPastDue:
		return []byte(s), nil
	case SubscriptionStatusCanceled:
		return []byte(s), nil
	case SubscriptionStatusIncomplete:
		return []byte(s), nil
	case SubscriptionStatusIncompleteExpired:
		return []byte(s), nil
	case SubscriptionStatusUnpaid:
		return []byte(s), nil
	case SubscriptionStatusPaused:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SubscriptionStatus) UnmarshalText(data []byte) error {
	switch SubscriptionStatus(data) {
	case SubscriptionStatusActive:
		*s = SubscriptionStatusActive
		return nil
	case SubscriptionStatusTrialing:
		*s = SubscriptionStatusTrialing
		return nil
	case SubscriptionStatusPastDue:
		*s = SubscriptionStatusPastDue
		return nil
	case SubscriptionStatusCanceled:
		*s = SubscriptionStatusCanceled
		return nil
	case SubscriptionStatusIncomplete:
		*s = SubscriptionStatusIncomplete
		return nil
	case SubscriptionStatusIncompleteExpired:
		*s = SubscriptionStatusIncompleteExpired
		return nil
	case SubscriptionStatusUnpaid:
		*s = SubscriptionStatusUnpaid
		return nil
	case SubscriptionStatusPaused:
		*s = SubscriptionStatusPaused
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/SubscriptionSummary
type SubscriptionSummary struct {
	ID                uuid.UUID          `json:"id"`
	PriceKey          string             `json:"priceKey"`
	Status            SubscriptionStatus `json:"status"`
	CurrentPeriodEnd  OptDateTime        `json:"currentPeriodEnd"`
	CancelAtPeriodEnd bool               `json:"cancelAtPeriodEnd"`
}

// GetID returns the value of ID.
func (s *SubscriptionSummary) GetID() uuid.UUID {
	return s.ID
}

// GetPriceKey returns the value of PriceKey.
func (s *SubscriptionSummary) GetPriceKey() string {
	return s.PriceKey
}

// GetStatus returns the value of Status.
func (s *SubscriptionSummary) GetStatus() SubscriptionStatus {
	return s.Status
}

// GetCurrentPeriodEnd returns the value of CurrentPeriodEnd.
func (s *SubscriptionSummary) GetCurrentPeriodEnd() OptDateTime {
	return s.CurrentPeriodEnd
}

// GetCancelAtPeriodEnd returns the value of CancelAtPeriodEnd.
func (s *SubscriptionSummary) GetCancelAtPeriodEnd() bool {
	return s.CancelAtPeriodEnd
}

// SetID sets the value of ID.
func (s *SubscriptionSummary) SetID(val uuid.UUID) {
	s.ID = val
}

// SetPriceKey sets the value of PriceKey.
func (s *SubscriptionSummary) SetPriceKey(val string) {
	s.PriceKey = val
}

// SetStatus sets the value of Status.
func (s *SubscriptionSummary) SetStatus(val SubscriptionStatus) {
	s.Status = val
}

// SetCurrentPeriodEnd sets the value of CurrentPeriodEnd.
func (s *SubscriptionSummary) SetCurrentPeriodEnd(val OptDateTime) {
	s.CurrentPeriodEnd = val
}

// SetCancelAtPeriodEnd sets the value of CancelAtPeriodEnd.
func (s *SubscriptionSummary) SetCancelAtPeriodEnd(val bool) {
	s.CancelAtPeriodEnd = val
}
