// Code generated by ogen, DO NOT EDIT.

package billingapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateCheckoutSession implements createCheckoutSession operation.
	//
	// Create a Stripe Checkout session for a server-controlled price.
	//
	// POST /api/organizations/{organizationId}/billing/checkout-sessions
	CreateCheckoutSession(ctx context.Context, req *CreateCheckoutSessionInput, params CreateCheckoutSessionParams) (CreateCheckoutSessionRes, error)
	// CreatePortalSession implements createPortalSession operation.
	//
	// Create a Stripe Customer Portal session.
	//
	// POST /api/organizations/{organizationId}/billing/portal-sessions
	CreatePortalSession(ctx context.Context, params CreatePortalSessionParams) (CreatePortalSessionRes, error)
	// GetBillingSummary implements getBillingSummary operation.
	//
	// Get the organization's current billing/entitlement summary.
	//
	// GET /api/organizations/{organizationId}/billing/summary
	GetBillingSummary(ctx context.Context, params GetBillingSummaryParams) (GetBillingSummaryRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
